name: habllen
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  sales_api:
    path: packages/sales_api
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_auth: ^3.1.2
  firebase_core: ^1.0.2
  cloud_firestore: ^2.5.3
  flow_builder: ^0.0.2
  flutter_bloc: ^7.3.0
  formz: ^0.4.0-nullsafety.0
  google_sign_in: ^5.0.1
  googleapis: ^5.0.1
  googleapis_auth: ^1.1.0
  http: ^0.13.1
  rxdart: ^0.27.1
  path_provider: ^2.0.2
  flutter_pdfview: ^1.0.4
  printing: ^5.6.0
  date_field: ^2.1.2
  connectivity_plus: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null

flutter:
  assets:
    - assets/1.jpg
    - assets/Roboto-Regular.ttf
    - assets/blank-profile-picture.png
  uses-material-design: true
