name: authentication_repository
description: A new Flutter package project.
version: 0.0.1
homepage: null
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  firebase_auth: ^3.1.2
  firebase_core: ^1.10.6
  google_sign_in: ^5.2.1
  meta: ^1.3.0
  freezed_annotation: ^1.1.0

    

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  freezed: ^1.1.1

flutter: null

